version: "3"
services:
    php:
        build:
            context: ./
        volumes:
            - .:/app:cached
        working_dir: /app
        container_name: nt_coordinates_resolver_php

    nginx:
        image: nginx:1.15.8-alpine
        ports:
            - 127.0.0.1:${NGINX_PORT}:80
        volumes:
            - .:/app:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
        container_name: nt_coordinates_resolver_nginx

    mysql:
        image: mysql:5.7
        volumes:
            - ./docker/mysql/data:/var/lib/mysql:cached
        ports:
            - 127.0.0.1:${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DB_NAME: ${MYSQL_DB_NAME}
        container_name: nt_coordinates_resolver_mysql
